version: '3.9'

services:
  server:
    build: ./../DeliveryOrderSystem/.
    ports:
      - "8000:80"
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6432:5432"
    restart: unless-stopped
    